# dev - install node_modules only, get files from local
FROM node:10
WORKDIR /app
COPY package.json .

RUN npm install
RUN npm install -g nodemon

ADD ./app

RUN npm run tsc

RUN export HOST_IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)

